### ISSUE TITLE
及時更新英文參照檔案

### ISSUE THREAD

**Issue by lakejason0** [Dianliang233/minecraft-lzh#16]
在新快照或版本出來後，請按照以下流程更新“en_us_ref.json”：
1. 進對應的`.minecraft/versions`文件夾（Windows位於`%APPDATA%`下）
2. 解包對應的jar文件
3. 進入`assets/minecraft/lang`將`en_us.json`提取出來
4. 將內容複製到repo的`en_us_ref.json`，並推送更新

感謝各位！

如果有餘力的話，可以幫忙把英文的字符串按照英文本身的順序搬運過來。注意，按照“按多更新”的原則，如果英文檔案修改了翻譯關鍵字，那麼文言文檔案應該新增而非修改。所有的值，如果沒把握翻譯，那麼請刪除裏面的英文。

**Comment by MineCreeper86** [comment]
Windows可以从.jar里找`/assets/lang/en_us.json`不用`%APPDATA%`

**Comment by MiemieMethod** [comment]
> Windows可以从.jar里找`/assets/lang/en_us.json`不用`%APPDATA%`

附議，此簡之解極也

**Comment by lakejason0** [comment]
> Windows可以从.jar里找`/assets/lang/en_us.json`不用`%APPDATA%`

jar在%APPDATA%内
