### ISSUE TITLE
關於Crowdin

### ISSUE THREAD

**Issue by teddyxlandlee** [Dianliang233/minecraft-lzh#31]
[Crowdin](https://crowdin.com/project/minecraft/lzh#)之譯，屬實貴工作室之發起哉？斯頗黯淡，無人問津。其審核者，茶館人乎？與本倉何干？須廣而告之，有人審矣。

**Comment by Dianliang233** [comment]
Minecraft 游戏内的翻译，由本工作室成员发起，但不由本工作室维护，与本工作室没有任何关系，但是经我工作室的特别授权，沿用了本工作室资源包的翻译文本。

**Comment by Dianliang233** [comment]
若您对项目感兴趣，欢迎加入 QQ 群：668387768

**Comment by teddyxlandlee** [comment]
感谢！

**Comment by teddyxlandlee** [comment]
（但是Mojang大大看起来有点慵懒的亚子，根本不审。贵工作室是否考虑派亿名审核员（~~干 涉 内 政~~

**Comment by Dianliang233** [comment]
> （但是Mojang大大看起来有点慵懒的亚子，根本不审。贵工作室是否考虑派亿名审核员（~干 涉 内 政~

Minecraft 的简体中文和文言文翻译由中文 Minecraft Wiki 管理团队负责。本工作室虽然有三位成员也是 wiki 管理团队成员，但我们没有、也不会有兴趣干涉其校对工作。

**Comment by teddyxlandlee** [comment]
（懂了，这就去催铁镐人
